bloodbankms/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    # path('', views.AppointmentListView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('inventory/', include('inventory.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

inventory/urls.py
from django.urls import path
from .views import (
    InventoryListView,
    InventoryUpdateView,
    InventoryDetailView,
    InventoryDeleteView,
    InventoryCreateView,
    AppointmentListView,
    AppointmentUpdateView,
    AppointmentDetailView,
    AppointmentDeleteView,
    AppointmentCreateView
)

app_name = 'inventory'

urlpatterns = [
    path('inventory/', InventoryListView.as_view(), name='inventory_list'),
    path('inventory/<int:pk>/edit/',
         InventoryUpdateView.as_view(), name='inventory_edit'),
    path('inventory/<int:pk>/',
         InventoryDetailView.as_view(), name='inventory_detail'),
    path('inventory/<int:pk>/delete/',
         InventoryDeleteView.as_view(), name='inventory_delete'),
    path('inventory/new/', InventoryCreateView.as_view(), name='inventory_new'),

    path('appointments/', AppointmentListView.as_view(), name='appointment_list'),

    path('appointments/<int:pk>/edit/',
         AppointmentUpdateView.as_view(), name='appointment_edit'),
    path('appointments/<int:pk>/',
         AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointments/<int:pk>/delete/',
         AppointmentDeleteView.as_view(), name='appointment_delete'),
    path('appointments/new/', AppointmentCreateView.as_view(), name='appointment_new'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import DonorCreateView, DonorDetailView, DonorListView, DonorDeleteView, DonorUpdateView, RecipientCreateView, RecipientDetailView, RecipientListView, RecipientDeleteView, RecipientUpdateView, SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(template_name='signup.html'), name='signup'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset-form/', auth_views.PasswordResetView.as_view(), name='password_reset_form'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('donors', DonorListView.as_view(), name='donor_list'),
    path('donors/<int:pk>/edit/', DonorUpdateView.as_view(), name='donor_edit'),
    path('donors/<int:pk>/', DonorDetailView.as_view(), name='donor_detail'),
    path('donors/<int:pk>/delete/', DonorDeleteView.as_view(), name='donor_delete'),
    path('donors/new/', DonorCreateView.as_view(), name='donor_new'),


    path('recipients', RecipientListView.as_view(), name='recipient_list'),
    path('recipients/<int:pk>/edit/', RecipientUpdateView.as_view(), name='recipient_edit'),
    path('recipients/<int:pk>/', RecipientDetailView.as_view(), name='recipient_detail'),
    path('recipients/<int:pk>/delete/', RecipientDeleteView.as_view(), name='recipient_delete'),
    path('recipients/new/', RecipientCreateView.as_view(), name='recipient_new'),
]

templates/appointment_list.html
{% extends 'base.html' %}

{% block title %}Appointment{% endblock title %}

{% block content %}
<section>
    <div class="row">
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Donor</th>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Associated Staff</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for appointment in object_list %}
            <tr>
                <td>{{ appointment.id  }}</td>
                <td>{{ appointment.donor  }}</td>
                <td>{{ appointment.appointment_date  }}</td>
                <td>{{ appointment.start_time |time:"h:i A" }}</td>
                <td>{{ appointment.end_time |time:"h:i A" }}</td>
                <td>{{ appointment.staff }} </td>
                <td><a href="{% url 'inventory:appointment_edit' appointment.pk %}">Edit</a></td>
                <td><a href="{% url 'inventory:appointment_delete' appointment.pk %}">Delete</a></td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block name %}Blood Bank{% endblock name %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'home' %}">Blood Bank Management System</a>
      {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <a href="{% url 'users:donor_new' %}">New Donor</a>&emsp;&emsp;
          <tr/>
          <a href="{% url 'users:recipient_new' %}"> New Recipient</a>&emsp;&emsp;
           <tr/>
          <a href="{% url 'inventory:inventory_new' %}">Add Inventory</a>&emsp;&emsp;
          <tr/>
          <a href="{% url 'inventory:appointment_new' %}">New Appointment</a>
        </ul>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
              data-toggle="dropdown" aria-haspopup="true" aria-expanded\
              ="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right"
              aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
            Log In</a>
             <a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">
            Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

templates/donor_list.html
{% extends 'base.html' %}

{% block title %}Donors{% endblock title %}

{% block content %}
{% for donor in object_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ donor.name }} </span>
    </div>
    <div class="card-body">
        <table>
            <tr>
                <td style="column-width:300px">
                    <span class="font-muted">Age: {{ donor.age }}</span> <br/>
                    <span class="font-muted">Blood Type: {{ donor.blood_type }} </span><br/>
                    <span class="font-muted">Address: {{ donor.address }} </span><br/>
                </td>
                <td>
                    <span class="font-muted">Phone Num: {{ donor.phone_num }} </span><br/>
                    <span class="font-muted">Email: {{ donor.email }}</span><br/>
                    <span class="font-muted-">Gender: {{ donor.gender }}</span>
                </td>
            </tr>
        </table>
    </div>
    <div class="card-footer">
        <a href="{% url 'users:donor_edit' donor.pk %}">Edit</a> |
        <a href="{% url 'users:donor_delete' donor.pk %}">Delete</a>
    </div>
</div>
<br/>
{% endfor %}
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Blood Bank Management System</h1>
    <p class="lead">Donor, Recipient and Inventory Management System.</p>
    {% if user.is_authenticated %}

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="{% url 'users:donor_list' %}">Donors</a>
                &emsp;&emsp;
            </li>
            <li class="nav-item">
                <a href="{% url 'users:recipient_list' %}">Recipient Requests </a>
                &emsp;&emsp;
            </li>
            <li class="nav-item">
                <a href="{% url 'inventory:inventory_list' %}">Inventory</a>
                &emsp;&emsp;
            </li>
            <li class="nav-item">
                <a href="{% url 'inventory:appointment_list' %}">Appointments</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock content %}

templates/inventory_list.html
{% extends 'base.html' %}

{% block title %}Inventory{% endblock title %}

{% block content %}
  {% for inventory in object_list %}
    <div class="card">
      <div class="card-header">
        <span class="font-weight-bold">Blood Type: {{ inventory.blood_type }} | </span>
        <span class="font-weight-bold">Date of Donation: {{ inventory.date_of_donation }} </span>
      </div>
      <div class="card-body">
        <p>Donor : {{inventory.appointment.donor}}</p>
        <p>Recipient: {{ inventory.recipient }}</p>
      </div>
      <div class="card-footer">
        <a href="{% url 'inventory:inventory_edit' inventory.pk %}">Edit</a> |
        <a href="{% url 'inventory:inventory_delete' inventory.pk %}">Delete</a>
      </div>
    </div>
    <br />
  {% endfor %}
{% endblock content %}

templates/recipient_list.html
{% extends 'base.html' %}

{% block title %}Recipients{% endblock title %}

{% block content %}
{% for recipient in object_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ recipient.name }} </span>
    </div>
    <div class="card-body">
        <p>Phone Num: {{ recipient.phone_num }} </p>
        <p>Address : {{recipient.address}}</p>
        <p>Blood Type: {{ recipient.blood_type }}</p>
        <p>Date of Request: {{ recipient.date_of_request }}</p>
    </div>
    <div class="card-footer">
        <a href="{% url 'users:recipient_edit' recipient.pk %}">Edit</a> |
        <a href="{% url 'users:recipient_delete' recipient.pk %}">Delete</a>
    </div>
</div>
<br/>
{% endfor %}
{% endblock content %}